version: '3.3'

services:
    nginx:
        image: nginx
        ports:
            - "8000:8000"
        volumes:
            - ./src:/src
            - ./config/nginx:/etc/nginx/conf.d
           # - ./src/static:/src/static
        depends_on:
            - web
    db:
        image: postgres
        restart: always
    web:
        build: .
        command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn emprl.wsgi -b 0.0.0.0:8000"
        volumes: 
            - ./src:/src
           # - ./src/static:/src/static
        expose:
            - "8000"
        depends_on:
            - db
            
        
    